bin/detect should write app type to stdout

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,7 +2,10 @@
 
 # This pack requires your app to have an nginx.conf.erb at conf/
 
-[ -f "$1/conf/nginx.conf.erb" ] && exit 0
-
-echo "Could not find conf/nginx.conf.erb, build cannot continue."
-exit 1
+if [ -f "$1/conf/nginx.conf.erb" ]; then
+	echo "Nginx"
+	exit 0
+else
+	echo "Could not find conf/nginx.conf.erb, build cannot continue."
+	exit 1
+fi
